run:
  go: "1.19"

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - funlen

linters:
  enable-all: true

  disable:
    # deprecated
    - maligned
    - scopelint
    - varcheck
    - interfacer
    - structcheck
    - nosnakecase
    - deadcode
    - exhaustivestruct
    - ifshort
    - golint

    # others
    - forbidigo

    # to evaluate
    - varnamelen
    - noctx
    - gomnd
    - gochecknoglobals
    - exhaustruct
    - godox
    - paralleltest
    - depguard
